export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Zeynep Yılmaz",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Mehmet Demir",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Ayşe Kaya",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Elif Şahin",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Fatma Çelik",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Havva Özkan",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Aslı Aydın",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Derya Koç",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Selin Yıldırım",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Zeynep Yılmaz",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Herkes için sevgi, kimse için nefret.",
    photo: "assets/post/1.jpeg",
    date: "5 dakika önce",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 dakika önce",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Her an yeni bir başlangıçtır.",
    photo: "assets/post/3.jpeg",
    date: "1 saat önce",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 saat önce",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 saat önce",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 gün önce",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Seni gülümseten hiçbir şey için pişman olma.",
    photo: "assets/post/7.jpeg",
    date: "2 gün önce",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 gün önce",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Dünyayı değiştirmek istiyorsan, önce kendin ol.",
    photo: "assets/post/9.jpeg",
    date: "5 gün önce",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 hafta önce",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
